"""Camada de orquestração: estado do run, executor e, futuramente, estágios."""
from app.orchestration.executor import start_run
from app.orchestration.state import (
    RUN_STAGES,
    RunCancelled,
    RunStageState,
    RunState,
    active_run_for_project,
    check_cancelled,
    create_run,
    create_run_if_none,
    get_run,
    mark_run_cancelled,
    mark_run_completed,
    mark_run_failed,
    mark_run_started,
    request_cancel,
    run_snapshot,
    update_stage,
)

__all__ = [
    "RUN_STAGES",
    "RunCancelled",
    "RunStageState",
    "RunState",
    "active_run_for_project",
    "check_cancelled",
    "create_run",
    "create_run_if_none",
    "get_run",
    "mark_run_cancelled",
    "mark_run_completed",
    "mark_run_failed",
    "mark_run_started",
    "request_cancel",
    "run_snapshot",
    "start_run",
    "update_stage",
]
