"""Fachada compatível dos schemas Pydantic.

As definições reais ficam organizadas por domínio em app.schema_groups.
"""

from app.schema_groups.api import ManualMediaItemCreate, OfficialFactCreate, ProjectCreate
from app.schema_groups.base import StrictLLMOutput
from app.schema_groups.search import (
    AgentBulkQueryResult,
    AgentBulkSearchArgs,
    AgentBulkSearchResponse,
    AgentSearchHit,
    AgentSearchResponse,
    AgentWebSearchArgs,
    CollectorExecutionResponse,
)
from app.schema_groups.social import (
    PublicOpinionIndicatorOutput,
    PublicOpinionSurveyExtractionResponse,
    SocialCommentAssessment,
    SocialCommentBatchResponse,
    SocialDiscourseAnalysisResponse,
    SocialNarrativeOutput,
)
from app.schema_groups.research import (
    AcademicPaperSelection,
    AcademicResearchResponse,
    AcademicSearchToolResponse,
    AcademicToolPaper,
    AgentAcademicSearchArgs,
    AgentBulkArticleFetchArgs,
    ArticleFetchItemResult,
    ArticleFetchToolResponse,
    HydrationExecutionResponse,
)
from app.schema_groups.planning import (
    GapFillQuery,
    GapFillResponse,
    InstitutionalProductProfileResponse,
    OfficialFactOutput,
    ProcessDecision,
    ReportPlanResponse,
    SearchPlanItem,
    SearchPlanResponse,
    SearchStrategyResponse,
    TopicProfileResponse,
    TopicRuleSet,
)
from app.schema_groups.facts import (
    FactEventOutput,
    FactExtractionResponse,
    FactFieldOutput,
    MediaClassificationBatchResponse,
    MediaClassificationOutput,
    MediaRelevanceBatchResponse,
    MediaRelevanceDecision,
    YouTubeCrossValidationResponse,
)
from app.schema_groups.reporting import (
    PressKitOutput,
    QAFindingOutput,
    ReportQAResponse,
    RiskAssessmentOutput,
    StructuredMediaReportResponse,
    ThematicAxisOutput,
)
from app.schema_groups.chat import ChatAskRequest, ChatResponse, ChatTurnIn

__all__ = [
    "ProjectCreate",
    "OfficialFactCreate",
    "ManualMediaItemCreate",
    "StrictLLMOutput",
    "AgentWebSearchArgs",
    "AgentSearchHit",
    "AgentSearchResponse",
    "AgentBulkSearchArgs",
    "AgentBulkQueryResult",
    "AgentBulkSearchResponse",
    "CollectorExecutionResponse",
    "SocialCommentAssessment",
    "SocialCommentBatchResponse",
    "SocialNarrativeOutput",
    "SocialDiscourseAnalysisResponse",
    "AgentAcademicSearchArgs",
    "AcademicToolPaper",
    "AcademicSearchToolResponse",
    "AcademicPaperSelection",
    "AcademicResearchResponse",
    "AgentBulkArticleFetchArgs",
    "ArticleFetchItemResult",
    "ArticleFetchToolResponse",
    "HydrationExecutionResponse",
    "TopicRuleSet",
    "TopicProfileResponse",
    "OfficialFactOutput",
    "InstitutionalProductProfileResponse",
    "SearchStrategyResponse",
    "ProcessDecision",
    "ReportPlanResponse",
    "SearchPlanItem",
    "SearchPlanResponse",
    "GapFillQuery",
    "GapFillResponse",
    "FactFieldOutput",
    "FactEventOutput",
    "FactExtractionResponse",
    "YouTubeCrossValidationResponse",
    "MediaRelevanceDecision",
    "MediaRelevanceBatchResponse",
    "MediaClassificationOutput",
    "MediaClassificationBatchResponse",
    "PublicOpinionIndicatorOutput",
    "PublicOpinionSurveyExtractionResponse",
    "ThematicAxisOutput",
    "RiskAssessmentOutput",
    "PressKitOutput",
    "StructuredMediaReportResponse",
    "QAFindingOutput",
    "ReportQAResponse",
    "ChatTurnIn",
    "ChatAskRequest",
    "ChatResponse",
]
